[general]
import = ["verdigris.toml"]

[font]
normal = { family = "Iosevka Nerd Font" }
size = 16.0

[window]
padding = { x = 4, y = 4 }

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
