# === Auto-start & Services ===
exec-once=pipewire
exec-once=sleep 1 && qs
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=nm-applet

# === Window Decorations & UI ===
rootcolor=0x0C2323ff
bordercolor=0x102C2Cff
focuscolor=0x143837ff
urgentcolor=0xB3653Cff

border_radius=8
borderpx=2
cursor_size=24
cursor_theme=Adwaita

layer_animations=1

animation_type_open=zoom
animation_type_close=slide
layer_animation_type_open=slide
layer_animation_type_close=slide
animation_fade_in=0
animation_fade_out=0
zoom_initial_ratio=0
zoom_end_ratio=1

animation_duration_move=400
animation_duration_open=400
animation_duration_tag=250
animation_duration_close=200

animation_curve_open=0.5,0,0,1
animation_curve_move=0.5,0,0,1
animation_curve_tag=0.5,0,0,1
animation_curve_close=0.5,0,0,1
animation_curve_focus=0.5,0,0,1

# === Layout & Gaps ===
gappih=8
gappiv=8
gappoh=8
gappov=8
trackpad_natural_scrolling=1
drag_warp_cursor=0
drag_tile_to_tile=1
new_is_master=0
default_mfact=0.5

# === Performance & Compatibility ===
xkb_rules_layout=tr

# === Keybindings: System & Apps ===
bind=SUPER,r,reload_config
bind=SUPER,q,killclient
bind=SUPER,Return,spawn,alacritty
bind=SUPER,space,spawn,qs ipc call launcher toggle
bind=SUPER,m,spawn,qs ipc call powerMenu toggle
bind=SUPER,c,spawn,qs ipc call clipboard toggle

# === Keybindings: Window Management ===
bind=SUPER,t,togglefloating
bind=SUPER,f,togglefullscreen
bind=SUPER,j,focusstack,next
bind=SUPER,k,focusstack,prev
bind=ALT,Tab,focusstack,next
bind=SUPER,s,setlayout,scroller
bind=SUPER+SHIFT,s,setlayout,tile
axisbind=SUPER,UP,focusstack,prev
axisbind=SUPER,DOWN,focusstack,next

# === Keybindings: Workspaces ===
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0

# === Hardware Keys (Audio & Brightness) ===
bindl=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +5%
bindl=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 5%- --min-value 5%
bindl=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume --limit 1 @DEFAULT_SINK@ 5%+
bindl=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bindl=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bindl=NONE,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# === Mouse Bindings ===
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

windowrule=allow_csd:0,appid:.*
