# More option see https://github.com/DreamMaoMao/mango/wiki/

exec-once=pipewire
exec-once=qs

border_radius=8
borderpx=0

xkb_rules_layout=tr

trackpad_natural_scrolling=1

gappih=8
gappiv=8
gappoh=8
gappov=8

bind=SUPER,r,reload_config

bind=SUPER,space,spawn,qs ipc call launcher toggle
bind=SUPER,Return,spawn,alacritty

bind=SUPER,t,togglefloating
bind=SUPER,m,spawn,qs ipc call powermenu toggle
bind=SUPER,q,killclient,
bind=SUPER,l,spawn,qs ipc call lockscreen lock
bind=SUPER,v,spawn,qs ipc call clipboard toggle

bind=ALT,Tab,focusstack,next
bind=SUPER,j,focusstack,next
bind=SUPER,k,focusstack,prev

bind=SUPER,f,togglefullscreen,


bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0

bind=,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && qs ipc call osd display
bind=,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && qs ipc call osd display
bind=,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && qs ipc call osd display
bind=,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && qs ipc call osd displayMic
bind=,XF86MonBrightnessUp,spawn,brightnessctl set 5%+ && qs ipc call osd displayBrightness
bind=,XF86MonBrightnessDown,spawn,brightnessctl set 5%- && qs ipc call osd displayBrightness

bind=,Print,spawn,grim -g "$(slurp)" - | wl-copy

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

layer_animations=1
animation_type_open=zoom
animation_type_close=slide
layer_animation_type_open=slide
layer_animation_type_close=slide

animation_fade_in=0
animation_fade_out=0

zoom_initial_ratio=0
zoom_end_ratio=1

animation_duration_move=250
animation_duration_open=250
animation_duration_tag=250
animation_duration_close=250
animation_duration_focus=0

animation_curve_open=0.5,-0.5,0.5,1.5
animation_curve_move=0.5,-0.5,0.5,1.5
animation_curve_tag=0.5,-0.5,0.5,1.5
animation_curve_close=0.5,-0.5,0.5,1.5
animation_curve_focus=0.5,-0.5,0.5,1.5
animation_curve_opafadein=0.5,-0.5,0.5,1.5
animation_curve_opafadeout=0.5,-0.5,0.5,1.5

blur=1
blur_layer=1
blur_optimized=0
blur_params_radius=4
blur_params_num_passes=2
blur_params_noise=0.1
