#!/bin/sh

terminal=alacritty
menu="qs ipc call launcher toggle"

# Appearance
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

riverctl background-color 0x0e2524
riverctl border-width 2
riverctl border-color-focused 0xe4be9b
riverctl border-color-unfocused 0x153836
riverctl border-color-urgent 0xb63a3a
riverctl xcursor-theme Bibata-Original-Ice 24
riverctl rule-add ssd

# Behavior
riverctl focus-follows-cursor normal
riverctl set-repeat 50 250
riverctl keyboard-layout tr
riverctl default-attach-mode bottom

# Input
riverctl hide-cursor when-typing enabled
riverctl input "*Touchpad" tap enabled
riverctl input "*Touchpad" natural-scroll enabled
riverctl input "*Touchpad" disable-while-typing enabled
riverctl input "*Touchpad" disable-while-trackpointing enabled

# Mouse bindings
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Apps
riverctl map normal Super Return spawn $terminal
riverctl map normal Super Q      close
riverctl map normal Super Space  spawn "$menu"
riverctl map normal Super Escape spawn "qs ipc call powerMenu toggle"

# Layout
riverctl map normal Super J zoom
riverctl map -repeat normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map -repeat normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Windows
riverctl map normal Super T toggle-float
riverctl map normal Super F toggle-fullscreen

# Focus
riverctl map normal Alt       Tab focus-view previous

# Tags
for i in $(seq 1 9); do
    tags=$((1 << (i - 1)))
    riverctl map normal Super       "$i" set-focused-tags $tags
    riverctl map normal Super+Shift "$i" spawn "riverctl set-view-tags $tags && riverctl set-focused-tags $tags"
done

# Screenshots
riverctl map normal None Print spawn 'grim -g "$(slurp)" - | tee "$HOME/Pictures/$(date +%Y-%m-%d_%H-%M-%S).png" | wl-copy'

# Media keys
riverctl map -repeat normal None XF86AudioRaiseVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0"
riverctl map -repeat normal None XF86AudioLowerVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
riverctl map normal None XF86AudioMute         spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
riverctl map normal None XF86AudioMicMute      spawn "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
riverctl map -repeat normal None XF86MonBrightnessUp   spawn "brightnessctl set 5%+"
riverctl map -repeat normal None XF86MonBrightnessDown spawn "brightnessctl set 5%- -n 5%"

# Session
riverctl map normal Super+Shift Escape exit
